#cloud-config

coreos:
  fleet:
    metadata: master=true
  units:
  - name: kube-apiserver.service
    command: start
    content: |
      [Unit]
      Description=Kubernetes API Server
      Documentation=https://github.com/GoogleCloudPlatform/kubernetes
      Requires=etcd.service
      After=etcd.service
      [Service]
      ExecStart=/opt/bin/kube-apiserver \
      --address=0.0.0.0 \
      --port=8080 \
      --portal_net 10.101.0.0/16 \
      --etcd_servers=http://127.0.0.1:4001 \
      --public_address_override=$public_ipv4 \
      --logtostderr=true
      Restart=always
      RestartSec=10
  - name: kube-controller-manager.service 
    command: start
    content: |
      [Unit]
      Description=Kubernetes Controller Manager
      Documentation=https://github.com/GoogleCloudPlatform/kubernetes
      Requires=kube-apiserver.service
      After=kube-apiserver.service
      [Service]
      ExecStart=/opt/bin/kube-controller-manager \
      --master=127.0.0.1:8080 \
      --logtostderr=true
      Restart=always
      RestartSec=10
  - name: kube-scheduler.service
    command: start
    content: |
      [Unit]
      Description=Kubernetes Scheduler
      Documentation=https://github.com/GoogleCloudPlatform/kubernetes
      Requires=kube-apiserver.service
      After=kube-apiserver.service
      [Service]
      ExecStart=/opt/bin/kube-scheduler --master=127.0.0.1:8080
      Restart=always
      RestartSec=10
  - name: kube-register.service
    command: start
    content: |
      [Unit]
      Description=Kubernetes Registration Service
      Documentation=https://github.com/kelseyhightower/kube-register
      Requires=kube-apiserver.service
      After=kube-apiserver.service
      Requires=fleet.service
      After=fleet.service
      [Service]
      ExecStartPre=-/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/k8s/kube-register
      ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-register
      ExecStart=/opt/bin/kube-register \
      --metadata=minion=true \
      --fleet-endpoint=unix:///var/run/fleet.sock \
      --api-endpoint=http://127.0.0.1:8080
      Restart=always
      RestartSec=10